### ISSUE TITLE
Passthrough overview: include fully qualified domain name

### ISSUE THREAD

**Issue by nselikoff** [miragejs/site#1003]
The [overview section for passthrough](https://miragejs.com/docs/getting-started/overview/#passthrough) can be confusing for folks working on apps that primarily interact with external APIs at fully qualified domain names (like @achhunna and me). The first example says "on the current domain" but the second says "All other API requests will still pass through". Maybe including a commented out example with a FQDN would help, and/or a note about FQDNs linking to the [full API page for passthrough](https://miragejs.com/api/classes/server/#passthrough).

**Comment by nselikoff** [comment]
Basically we were taking the "slowly opt in" to mirage approach, but mirage was still catching all our requests because they were all going to FQDNs.

**Comment by samselikoff** [comment]
https://github.com/miragejs/site/commit/24126305f850ad5f1d56421899d7df0b8098cdc6

Think this would have helped?

(Btw passthrough is one of the most confusing parts of Mirage, especially during onboarding. We have some ideas for how to improve it but just wanted to mention others are running into issues like this too!)

**Comment by achhunna** [comment]
> [2412630](https://github.com/miragejs/site/commit/24126305f850ad5f1d56421899d7df0b8098cdc6)
> 
> Think this would have helped?
> 
> (Btw passthrough is one of the most confusing parts of Mirage, especially during onboarding. We have some ideas for how to improve it but just wanted to mention others are running into issues like this too!)

Awesome, thanks! 🥳

**Comment by nselikoff** [comment]
Perfect!
