### ISSUE TITLE
Don't include Mirage in React production builds

### ISSUE THREAD

**Issue by ryanto** [miragejs/site#110]
Tracking issue for excluding Mirage from CRA.

To explore:

* https://github.com/gsoft-inc/craco
* https://github.com/arackaf/customize-cra
* https://github.com/harrysolovay/rescripts
* https://github.com/marcopeg/create-react-app/blob/master/packages/react-scripts/README.md
* https://github.com/facebook/create-react-app/issues/3518 (Interesting approach to extending webpack in CRA)

**Comment by jgwhite** [comment]
We’re using `craco` on a production project. I don’t have any experience with it personally but haven’t heard the team complain about it 🤷‍♀️

**Comment by samselikoff** [comment]
@ryanto I believe https://github.com/miragejs/miragejs/pull/481 closes this - is that correct?

**Comment by ryanto** [comment]
Yup!
