### ISSUE TITLE
Change `overflow-y` from `scroll` to `auto` to hide the nav scrollbar when not needed

### ISSUE THREAD

**Issue by Flandre-X** [miragejs/site#1198]
# Problem

![Inkedchrome_yj9tOskTVO_LI](https://user-images.githubusercontent.com/38332081/130338031-d9321b49-38dd-44e4-8615-98250c938e28.jpg)

# Solution

![Inkedchrome_80HarwHApA_LI](https://user-images.githubusercontent.com/38332081/130338033-98f15347-9ef4-4735-830f-8e547f305870.jpg)

(Tested in Windows 10 Chrome)

**Comment by samselikoff** [comment]
Thanks for the report! I took a look but the site is not building right now :( I haven't been working on this a ton so it'd be a great help if anyone wants to take a closer look!

**Comment by Flandre-X** [comment]
@samselikoff There's a fix in #1199 (tested in Windows 10). It's just a change to `overflow-y-auto`, so hopefully it should be a trivial merge/ff. I don't use Windows any more, but this might be appreciated by those who do.

**Comment by samselikoff** [comment]
Sorry about that, looks like the build was fixed so I merged it!

**Comment by samselikoff** [comment]
https://github.com/miragejs/site/pull/1199 closes
