### ISSUE TITLE
Better fallback for non-SSR'd pages

### ISSUE THREAD

**Issue by samselikoff** [miragejs/site#42]
Our setup right now renders pages that haven't been SSR'd as `/` which ends up in screwy UI. SSR'ing pages dynamically using Router helps (#41) but it'd be good to have a more robust fallback in case SSR is absent and the app renders fully on client. Not sure why it doesn't work right now.

**Comment by ryanto** [comment]
Fixed in #295 

Basically we SSR everything, and if something fails SSR you'll see a 404 on netlify.
