### ISSUE TITLE
Mirage REPL window jumps to top when typing below viewport

### ISSUE THREAD

**Issue by Franatec** [miragejs/site#555]
Bug: When setting up server config in Mirage REPL and typing below the original viewport the focus jumps back to the top, presumably to the "loading" indicator, even though the cursor remain active at the end of the document.

Netscape 5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) **Chrome/81.0.4044.113** Safari/537.36

Don't need feedback, just reporting.

**Comment by samselikoff** [comment]
https://github.com/miragejs/site/pull/557 fixes, let me know if you still see any issues!
