### ISSUE TITLE
Add Next.js setup guide

### ISSUE THREAD

**Issue by samselikoff** [miragejs/site#69]

**Comment by GriffinSauce** [comment]
This would be great! Just spitballing: if you avoid SSR for pages it seems like Mirage could be initiated in `_app.js` and you'd be good to go.

**Comment by GriffinSauce** [comment]
I've attempted that but haven't been able to get it to work, perhaps because of the nextjs fetch polyfill? It's not really clear why Pretender isn't picking up on the requests.

Repo: https://github.com/GriffinSauce/nextjs-mirage-example

@timneutkens any chance you or a team member could take a look at this?

**Comment by ryanto** [comment]
Thanks @GriffinSauce ! 

I just gave it a shot and think you're right about it having to do with the polyfill. The way that we (pretender) intercept fetch requests is by installing the whatwg-fetch polyfill, which changes window.fetch to use XMLHttpRequest, and then we rely on pretender to pickup those outgoing XMLHttpRequests.

We'll need to investigate more, and probably come up with another way to catch these fetch requests in a next friendly way.

**Comment by GriffinSauce** [comment]
I've done a little digging. Seems like next.js already polyfills with whatwg:

https://github.com/zeit/next.js/blob/ecd628b7e0619da7677b57138a7dd59c1b581b59/packages/next/build/webpack-config.ts#L77

Imported here:

https://github.com/zeit/next.js/blob/04a7f1e85d34c72a3d45a05f4ca9d158ef1b5af0/packages/next/client/polyfills.js

And loaded here:

https://github.com/zeit/next.js/blob/2fe743581471279497b53ed692ff77c01be73e93/packages/next/pages/_document.tsx#L622

They make a specific effort to load this before anything else. Perhaps customising the webpack config to alias the modules could work but that greatly diminishes the DX and maintainability.

Didn't have time to try anything else yet, but it looks pretty tricky. :(

**Comment by samselikoff** [comment]
Update: https://github.com/zeit/next.js/issues/10509#issuecomment-585517476

**Comment by GriffinSauce** [comment]
Just to let you know, I just patched in the new pretender version via yarn resolution and it works!

**Comment by ryanto** [comment]
Nice! Awesome to hear!

I think we should get mirage released and the website updated with the nextjs example this week.

**Comment by Saikat180891** [comment]
Even I am trying to add MirageJs to Next app and I am finding it difficult. In browser if I write http://localhost:3000/api/users I am getting 404 although my mirage server is running.

**Comment by samselikoff** [comment]
Can finally close this – all the changes have been made so Mirage works w/Next.js for client-side API requests out of the box!

https://miragejs.com/quickstarts/nextjs/develop-a-page/

**Comment by GriffinSauce** [comment]
🙌 Thanks Sam!
